Creating the Homepage
a-laarabi/Portfolio pull request #1
Opened 2022-05-27 03:19 UTC by a-laarabi

## What?
I've added an HTML Homepage to the project

## Why?
Learning.

## How?
Creating an .html and .css files

2022-05-27 04:15 UTC, Kakalanp requested changes
# Hello there @a-laarabi! <img src="https://user-images.githubusercontent.com/1303154/88677602-1635ba80-d120-11ea-84d8-d263ba5fc3c0.gif" width="28px" alt="hi">

### Good job so far! :tada: 

There are some issues that you still need to work on to go to the next project but you are almost there! :pinching_hand: 

<img src="https://media.giphy.com/media/Qaxd5XpgDWMso/giphy.gif" alt="so close">

## Highlights :+1: 
- No linter errors :heavy_check_mark:
- Repo looks professional :briefcase:
- Solid pull request :scroll:
- Espectacular UI design! :monocle_face: 
- Excellent use of best practices :fire: 

## Required Changes ♻️
***Check the comments under the review.***

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 04:15 UTC, Kakalanp commented on index.html
> +    <div class="header_body">
It's considered good practice to separate **section**s of a page with `<section>` tags, kindly change this `<div>` to a `<section>` :sparkles:

2022-05-27 04:15 UTC, Kakalanp commented on index.html
> +        <h2>I’m Anasse<br>Glad to see you!</h2>
As this is the main title of your page, using an `<h1>` would be the most appropriate way of using best practices, as well as using `<h2>`, `<h3>`, `<h4>`, and `<h5>` in a hierarchical manner for subtitles :grin:

2022-05-27 04:15 UTC, Kakalanp commented on index.html
> +            <li><a href="#"><img src="img/angellist.png" alt="angellist"></a></li>
Excellent way of using `<ul>` and `<li>`! Just don't forget to add the respective links :smiley:

2022-05-27 04:15 UTC, Kakalanp commented on style.css
> +  background: url('img/bg_Header.png');
Your background image seems a little off, consider using the mobile one! :eyes:

2022-05-27 04:15 UTC, Kakalanp commented on style.css
> +}
The page seems to be too wide on my screen, it could easily be a chrome bug, but, to prevent this kind of interaction, you can always remove margins from your body or every element(the CSS selector for all is `*`) :thinking:

2022-05-27 04:15 UTC, Kakalanp commented on index.html
> +    </nav>
Don't forget that the mobile version is supposed to have a hamburger button and hidden links for the sections of the page :+1:

2022-05-27 20:33 UTC, merged

2022-05-28 03:08 UTC, Lucas-Masaba reviewed
# Hello @a-laarabi  👋 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![almost-there](https://media.giphy.com/media/dEPGknRiEniec/giphy.gif)

 ## Highlights 🍾 
- Linter checks passing ✔️ 
- Applied most changes requested by the previous reviewer 👍 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [ ] Your template design does not resemble that of the Figma template. Please add all necessary font sizes, margins, padddings and so on so that it looks similar to that of the Figma.
### Your Implementation
![image](https://user-images.githubusercontent.com/45460192/170807414-80a1205b-0680-4b0a-bc75-d2036542c3a2.png)
### Figma(Required)
![image](https://user-images.githubusercontent.com/45460192/170807484-c2d9d531-157e-48a8-a046-be7951efd2ba.png)

2022-05-28 03:08 UTC, Lucas-Masaba commented on index.html
> +    </nav>
[ ] The previous reviewer meant to say that only the hamburger menu button is to appear. Not the portfolio, about or contact links. Please remove those and replace them with a hamburger button. Your header should look like this 👌 
![image](https://user-images.githubusercontent.com/45460192/170807285-3668d11b-33de-4641-b811-406747795d2e.png)